path = "/home/runner/esp/idf"
idf_path = "/home/runner/esp/idf/v5.5/esp-idf"
esp_idf_json_path = "/home/runner/.espressif/tools"
tool_download_folder_name = "/home/runner/.espressif/dist"
tool_install_folder_name = "~/.espressif"
target = ["all"]
idf_versions = ["v5.5"]
tools_json_file = "tools/tools.json"
config_file_save_path = "eim_config.toml"
non_interactive = true
wizard_all_questions = false
mirror = "https://github.com"
idf_mirror = "https://github.com"
pypi_mirror = "https://pypi.org/simple"
recurse_submodules = true
install_all_prerequisites = true
skip_prerequisites_check = false
python_env_folder_name = "python"
activation_script_path_override = "/home/runner/.espressif/tools"
python_version_override = "python313"

[idf_features_per_version]
"v5.5" = ["core"]
